version: '3.8'

services:
  backend:
    build: 
      context: ./src/backend
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    environment:
      - FLASK_ENV=development

  frontend:
    build: 
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - "/usr/src/frontend/node_modules"
    depends_on:
      - backend